apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-route-operator
  namespace: platform
rules:
  - apiGroups:
      - platform.saca.pags
    resources:
      - gatewayroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - gateway-routes
    verbs:
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-route-operator
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-route-operator
subjects:
  - kind: ServiceAccount
    name: gateway-route-operator
    namespace: platform