apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: platform
  labels:
    app.kubernetes.io/name: nginx-lb
    app.kubernetes.io/part-of: dynamic-gateway-control-plane
    app.kubernetes.io/component: edge-lb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-lb
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
